language: python
python:
  - "2.7"
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script:
  - python -c "from lib.core.link import Link"
  - python -c "from optparse import OptionParser"
  - python -c "from lib.core.engine import links"
  - python -c "from lib.core.engine import getPage"
  - python -c "from lib.core.engine import getScript"
  - python -c "from lib.core.engine import xssScanner"
  - python -c "from lib.generator.report import gnrReport"
